[workspace]
authors = ["Masao-Someki <masao.someki@gmail.com>"]
channels = ["conda-forge"]
name = "03_OWSM_finetuning"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pip = ">=26.0.1,<27"
datasets = ">=4.6.0,<5"
typeguard = ">=4.5.1,<5"

#add by dahee
libstdcxx-ng = ">=13"
libgcc-ng = ">=13"
