defaults:
  - ../owsm_peft_lora_basic

lr: 2e-5
exp_tag: exp_20260509_172915_lora_lr2e-5

peft:
  type: lora
  r: 8
  lora_alpha: 16
  lora_dropout: 0.1
  task_type: seq_2_seq_lm
  target_modules: ["linear_q", "linear_k", "linear_v", "linear_out", "w_1", "w_2"]
