recipedir: .
fleurs_repo: google/fleurs
fleurs_subsets_train: pt_br
fleurs_subsets_valid: pt_br
fleurs_subsets_test: pt_br
fleurs_cache_dir: ${recipedir}/cache/fleurs
lang_sym_mode: from_subset
max_samples_per_subset_train: null
max_samples_per_subset_valid: 50
max_samples_per_subset_test: null

dataset:
  _target_: espnet3.components.data.data_organizer.DataOrganizer
  recipe_dir: ${recipedir}
  train:
    - data_src_args:
        split: train
        hf_repo: ${fleurs_repo}
        hf_subsets: ${fleurs_subsets_train}
        cache_dir: ${fleurs_cache_dir}
        lang_sym_mode: ${lang_sym_mode}
        max_samples_per_subset: ${max_samples_per_subset_train}

  valid:
    - data_src_args:
        split: validation
        hf_repo: ${fleurs_repo}
        hf_subsets: ${fleurs_subsets_valid}
        cache_dir: ${fleurs_cache_dir}
        lang_sym_mode: ${lang_sym_mode}
        max_samples_per_subset: ${max_samples_per_subset_valid}

  preprocessor:
    _target_: espnet2.train.preprocessor.S2TCTCPreprocessor
    train: train
    token_type: bpe
    token_list: ${tokenizer.save_path}/tokens.txt
    bpemodel: ${tokenizer.save_path}/bpe.model
    text_prev_name: text_prev
    text_ctc_name: text_ctc
    fs: 16000
    na_symbol: <na>
    speech_length: 30
    speech_init_silence: 30
    text_prev_apply_prob: 0.5
    nolang_symbol: <unk>
