dataset:
  _target_: espnet3.components.data.data_organizer.DataOrganizer
  train:
    # ASR dataset
    - name:  train_falar # train_eurospeech
      dataset:
        # _target_: src.data.dataset.EuroSpeechPortugalDataset
        # data_dir: /work/nvme/bbjs/dyang10/datasets/eurospeech_portugal # add dahee
        _target_: src.data.dataset.FalarPortugalDataset
        split: train_0
        num_shards: 16
        world_shard_size: 4

  valid:
    # ASR data
    - name:  valid_falar # valid_eurospeech
      dataset:
        # _target_: src.data.dataset.EuroSpeechPortugalDataset
        # data_dir: /work/nvme/bbjs/dyang10/datasets/eurospeech_portugal # add dahee
        _target_: src.data.dataset.FalarPortugalSingleDataset
        split: dev

  test:
    - name: test_falar
      dataset:
        _target_: src.data.dataset.FalarPortugalSingleDataset
        split: test
  
  preprocessor:
    _target_: src.data.dataset.WhisperTokenizeTransform
    model_tag: openai/whisper-large-v3
