recipedir: .

exp_tag: default
exp_dir: ${recipedir}/exp/${exp_tag}
stats_dir: ${exp_dir}/stats #/work/nvme/bbjs/clin10/eurospeech_finetune/espnet/egs3/eurospeech_portugal/s2t1/exp/stats
dataset_dir: ""
seed: 2024
lr: 5e-5

num_device: 1
num_nodes: 1

parallel:
  env: local
  n_workers: 1

optimizer:
  _target_: torch.optim.AdamW
  lr: ${lr}
  weight_decay: 0.000001

scheduler:
  _target_: espnet2.schedulers.warmup_lr.WarmupLR
  warmup_steps: 6000


dataloader:
  collate_fn:
    _target_: espnet2.train.collate_fn.CommonCollateFn
    int_pad_value: -1
  train:
    iter_factory:
      _target_: espnet2.iterators.sequence_iter_factory.SequenceIterFactory
      shuffle: true
      collate_fn: ${dataloader.collate_fn}
      batches:
        type: numel
        shape_files:
          - ${stats_dir}/train/feats_shape
        batch_size: 4
        batch_bins: 200000
  valid:
    iter_factory:
      _target_: espnet2.iterators.sequence_iter_factory.SequenceIterFactory
      shuffle: false
      collate_fn: ${dataloader.collate_fn}
      batches:
        type: numel
        shape_files:
          - ${stats_dir}/valid/feats_shape
        batch_size: 4
        batch_bins: ${dataloader.train.iter_factory.batches.batch_bins}

best_model_criterion:
  - - valid/loss
    - 3
    - min

tokenizer:
  vocab_size: 50002
  character_coverage: 1.0
  model_type: bpe
  save_path: data/bpe_50000

trainer:
  max_epochs: 10
  precision: bf16-mixed
  accumulate_grad_batches: 1
  log_every_n_steps: 100
  gradient_clip_val: 5

  logger:
    - _target_: lightning.pytorch.loggers.WandbLogger
      project: Whisper_Finetuning_Portugal #OWSM Finetuning Portugal
      save_dir: ${exp_dir}/wandb
      name: default_lr${lr}

  strategy: auto

