# load default config
defaults:
  - default.yaml
  - dataset.yaml

lr: 5e-5
exp_tag: peft_randlora_lr${lr}

peft:
  type: randlora
  r: 32
  randlora_alpha: 640
  randlora_dropout: 0.0
  projection_prng_key: 0
  save_projection: true
  bias: none
  target_modules: ["linear_q", "linear_k", "linear_v", "linear_out", "w_1", "w_2"]

model:
  _target_: src.peft_model.OWSMFinetune
  model_tag: ${base_model_tag}
  peft: ${peft}
