# load default config
defaults:
  - default.yaml
  - dataset.yaml

lr: 5e-5
exp_tag: peft_lora_espnet_lr${lr}

peft:
  type: espnet_lora
  rank: 8
  alpha: 8
  dropout_rate: 0.05
  target_modules: ["linear_q", "linear_k", "linear_v", "linear_out", "w_1", "w_2"]

model:
  _target_: src.peft_model.OWSMFinetune
  model_tag: ${base_model_tag}
  peft: ${peft}

stats_dir: ${exp_dir}/stats # add dahee
