
# load default config
defaults:
  - default.yaml
  - dataset.yaml

lr: 5e-5
exp_tag: sanity_lr${lr}

model:
  _target_: src.model.OWSMFinetune
  model_tag: espnet/owsm_v4_medium_1B

trainer:
  fast_dev_run: false
  logger:
    - _target_: lightning.pytorch.loggers.WandbLogger
      project: ESPnet3 development
      save_dir: ${exp_dir}/wandb
      name: ${exp_tag}_lr${lr}
