
# load default config
defaults:
  - default.yaml
  - dataset.yaml

lr: 5e-5
exp_tag: sanity_lr${lr}

model:
  _target_: src.model.OWSMFinetune
  model_tag: ${base_model_tag}
trainer:
  fast_dev_run: false
