# load default config
defaults:
  - default.yaml
  - dataset.yaml

lr: 5e-5
exp_tag: peft_vblora_lr${lr}

peft:
  type: vblora
  r: 4
  num_vectors: 256
  vector_length: 256
  topk: 2
  vblora_dropout: 0.0
  bias: none
  target_modules: ["linear_q", "linear_k", "linear_v", "linear_out", "w_1", "w_2"]

model:
  _target_: src.peft_model.OWSMFinetune
  model_tag: ${base_model_tag}
  peft: ${peft}
