defaults:
  - ../../owsm_peft_adalora

lr: 5e-6
exp_tag: exp_20260509_011416_adalora_lr5e-6

peft:
  type: adalora
  r: 16
  lora_alpha: 16
  lora_dropout: 0.1
  task_type: seq_2_seq_lm
  target_modules: ["linear_q", "linear_k", "linear_v", "linear_out", "w_1", "w_2"]
