defaults:
  - ../../owsm_peft_lora_basic

lr: 3e-5
exp_tag: exp_20260509_004521_lora_lr3e-5

peft:
  type: lora
  r: 8
  lora_alpha: 16
  lora_dropout: 0.1
  task_type: seq_2_seq_lm
  target_modules: ["linear_q", "linear_k", "linear_v", "linear_out"]
