defaults:
  - ../default.yaml
  - ../dataset.yaml

exp_tag: exp_20260510_005653_ia3_long_targets

peft:
  type: ia3
  # hypothesis: restrict to key/v rather than broader set
  task_type: seq_2_seq_lm
  target_modules: ["linear_q", "linear_v"]

model:
  _target_: src.peft_model.OWSMFinetune
  model_tag: ${base_model_tag}
  peft: ${peft}

lr: 5e-5
