defaults:
  - ../default.yaml
  - ../dataset.yaml

exp_tag: exp_20260510_005653_lora_r16_alpha16

peft:
  type: lora
  r: 16
  lora_alpha: 16
  lora_dropout: 0.05
  task_type: seq_2_seq_lm
  target_modules: ["linear_q", "linear_k", "linear_v", "linear_out", "w_1", "w_2"]

model:
  _target_: src.peft_model.OWSMFinetune
  model_tag: ${base_model_tag}
  peft: ${peft}

lr: 5e-5
