defaults:
  - ../default.yaml
  - ../dataset.yaml

lr: 5e-5
exp_tag: exp_20260510_wave1_peft_methods_ln_tuning

peft:
  type: ln_tuning
  task_type: seq_2_seq_lm

model:
  _target_: src.peft_model.OWSMFinetune
  model_tag: ${base_model_tag}
  peft: ${peft}